phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js dependencies...
      - npm install

  build:
    commands:
      - echo Skipping build phase (not needed)

  post_build:
    commands:
      - echo Creating deployment package...
      - zip -r app.zip * .[^.]*

artifacts:
  files:
    - app.zip
