version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Skipping build step...

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*' # Optional: exclude node_modules for Elastic Beanstalk
